GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJDaGlzaWxpYSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzE3MDU0Nzk2LCJleHAiOjE3MTcwNTQ4MTF9.Mf3fH1vdxfZ9ecY_Kb_uYrknlRjl6tT8a28Yf4-hTi0
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Chisilia", 
    "email": "email@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token 

###
DELETE http://localhost:5000/logout